### ISSUE TITLE
hydrolakes and nhdplusv2 lake linking not working

### ISSUE THREAD

**Issue by lawinslow** [lawinslow/hydrolinks#20]
Both of these should work. That point is over Mendota, a fairly large lake that is in both datasets. hydrolakes dataset seems to download too many shapefiles, must be something wrong with bounding box. nhdplusv2 doesn't match at all. Projection issue? 

```
  testthat::expect_equal(nrow(link_to_waterbodies(43.108728, -89.418293, 'id1', dataset = 'hydrolakes')), 1)
  testthat::expect_equal(nrow(link_to_waterbodies(43.108728, -89.418293, 'id1', dataset = 'nhdplusv2')), 1)
```

**Comment by lawinslow** [comment]
@rainshapes want to take a look?

**Comment by lilyhahn** [comment]
besides the bounding boxes for nhdplusv2 being inaccurate i also misinterpreted the documentation and didn't unzip all the data - i'll fix this on wednesday.

**Comment by lawinslow** [comment]
OK, sounds good.
