### ISSUE TITLE
Force temporary directory use for all tests run

### ISSUE THREAD

**Issue by lawinslow** [lawinslow/hydrolinks#31]
Currently, tests save files in the appdata directory. It would make CRAN happier if tests didn't result in userspace file creation. For the examples and tests being run, switch the cache_location over to the R temp directory first. 

Otherwise, default can be left as-is.

**Comment by lilyhahn** [comment]
There's not a lot we can do right now - the location of the cache directory is written to the appdata directory when it's set and there isn't really a better place to store that.

**Comment by lawinslow** [comment]
Fixed in v0.7.1.
